
server:
  port: 8081
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    username: root
    password: 490416
    url: jdbc:mysql://localhost:3306/orderfood_db?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  #Spring boot视图配置

  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    mode: HTML
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html

#  thymeleaf:
#    prefix:
#      classpath: /templates/
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp
#      suffix: .jsp
#    #静态文件访问配置
#    static-path-pattern: /static/**



mybatis:
  mapper-locations: classpath:Mybatis/mapper/*Mapper.xml
  type-aliases-package: com.example.orderappservice.pojo
  configuration:
    map-underscore-to-camel-case: true

#showSql
logging:
  level:
    com:
      example:
        mapper : debug

